language: scala
matrix:
  include:
    - jdk: oraclejdk7
      scala: 2.11.8
    - jdk: oraclejdk8
      scala: 2.12.1
    - jdk: oraclejdk8
      scala: 2.12.3
script:
- sbt ++$TRAVIS_SCALA_VERSION compile test
